# Dataset training and validation splitter

This notebook splits the dataset among training and validation sets.

J. Irving Vasquez-Gomez

jivg.org

In [1]:
import numpy as np
import os

In [2]:
mydir = '../dataset/classification/'
file_vol = 'dataset_vol_classification.npy'
file_lbl = 'dataset_lbl_classification.npy'

path_input_vol = os.path.join(mydir, file_vol)
path_input_lbl = os.path.join(mydir, file_lbl)

In [4]:
dataset_vol = np.load(path_input_vol)
dataset_lbl = np.load(path_input_lbl)

print("Volumes data size: \n",dataset_vol.shape)
print("Labels data size: \n",dataset_lbl.shape)

Labels data size: 
 (13455, 1)


In [5]:
print(dataset_vol[1,:])

In [6]:
print(dataset_lbl)

print(np.unique(dataset_lbl))

[[9]
 [4]
 [3]
 ..., 
 [6]
 [9]
 [4]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]


In [20]:
# shuffle the dataset
n_examples = len(dataset_lbl)
print(n_examples)
shuffle = np.random.permutation(n_examples)
#print(shuffle)

train_percent = 0.8
vaidation_percent = 0.2

ds_lbl_train = dataset_lbl[shuffle[:int(n_examples * train_percent)],:]
ds_lbl_validation = dataset_lbl[shuffle[int(n_examples * train_percent):],:]

ds_vol_train = dataset_vol[shuffle[:int(n_examples * train_percent)],:]
ds_vol_validation = dataset_vol[shuffle[int(n_examples * train_percent):],:]


13455
[7891 1540  370 ..., 1935 9723 5237]
10764
2691


In [24]:
print(len(ds_lbl_train))
print(len(ds_lbl_validation))

print(dataset_lbl[shuffle,:])
print(ds_lbl_train)
print(ds_lbl_validation)

10764
2691
[[ 6]
 [ 7]
 [11]
 ..., 
 [ 5]
 [ 1]
 [ 5]]
[[ 6]
 [ 7]
 [11]
 ..., 
 [ 6]
 [ 8]
 [ 3]]
[[ 7]
 [ 5]
 [10]
 ..., 
 [ 5]
 [ 1]
 [ 5]]


In [26]:
#save the datasets

file_training_vol = os.path.join(mydir, 'training/dataset_vol_classification_training.npy')
file_validation_vol = os.path.join(mydir, 'validation/dataset_vol_classification_validation.npy')

file_training_lbl = os.path.join(mydir, 'training/dataset_lbl_classification_training.npy')
file_validation_lbl = os.path.join(mydir, 'validation/dataset_lbl_classification_validation.npy')

np.save(file_training_vol, ds_vol_train)
np.save(file_validation_vol, ds_vol_validation)

np.save(file_training_lbl, ds_lbl_train)
np.save(file_validation_lbl, ds_lbl_validation)